FROM python:2.7
MAINTAINER pi4homez <pi4homez@gmail.com>

RUN pip install --no-cache-dir platformio && \
    platformio settings set enable_telemetry No

COPY docker/platformio.ini /
RUN platformio run -e espressif32 -e espressif8266; exit 0
