[build]
  publish = "_build/html"
  command = "make netlify"
  environment = { BASE_URL = "https://pi4home.io" }

[context.beta]
  environment = { BASE_URL = "https://beta.pi4home.io" }

[context.next]
  environment = { BASE_URL = "https://next.pi4home.io" }

[context.production]
  environment = { BASE_URL = "https://pi4home.io", PRODUCTION = "YES" }

# A basic redirect rule
[[redirects]]
  from = "/pi4homeyaml/*"
  to = "/:splat"
