[build]
  publish = "_build/html"
  command = "make netlify"
  environment = { BASE_URL = "https://khzd/pi4home" }

[context.beta]
  environment = { BASE_URL = "https://beta.khzd/pi4home" }

[context.next]
  environment = { BASE_URL = "https://next.khzd/pi4home" }

[context.production]
  environment = { BASE_URL = "https://khzd/pi4home", PRODUCTION = "YES" }

# A basic redirect rule
[[redirects]]
  from = "/pi4homeyaml/*"
  to = "/:splat"
